### PR TITLE
fix 3.1 CI

### PR DESCRIPTION
**Pull request by simi**
:pray:

### CODE REVIEW

**Comment by simi** [comment]
@deivid-rodriguez still failing :/ Any idea?

**Comment by deivid-rodriguez** [comment]
Sorry @simi, which failures you were getting, I see CI stuck right now.

**Comment by deivid-rodriguez** [comment]
Oh, I see you just pushed it. Let's wait then.

**Comment by simi** [comment]
I tried restart to see if those failures are random.

**Comment by deivid-rodriguez** [comment]
@simi I think the currently failure is due to https://github.com/rubygems/bundler/pull/7565. I think you can cherry-pick that PR into the submodule.

**Comment by deivid-rodriguez** [comment]
Nice :)

**Pull request merged**
